version: "3.8"
services:
  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - SENTINEL_USER=${SENTINEL_USER}
      - SENTINEL_PASSWORD=${SENTINEL_PASSWORD}
